---
title: "p8105_hw3_rm3609"
author: "Runqi Ma"
date: "2018/10/14"
output: html_document
---


```{r}
library(tidyverse)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

#Problem 1 
###First, do some data cleaning:
format the data to use appropriate variable names;
focus on the “Overall Health” topic
include only responses from “Excellent” to “Poor”
organize responses as a factor taking levels ordered from “Excellent” to “Poor”

```{r}
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)
data(brfss_smart2010)

brfss_smart2010 = janitor::clean_names(brfss_smart2010) %>% 
  rename(resp_id = respid, location_abbr = locationabbr, location_desc = locationdesc) %>% 
  filter(topic == "Overall Health", 
         response %in% c("Excellent","Very good","Good","Fair","Poor"))

brfss_smart2010$response = as.factor(brfss_smart2010$response)
levels(brfss_smart2010$response) = c("Excellent","Very good","Good","Fair","Poor")  
brfss_smart2010
```


